export enum ReducerTypes {
    SET_ERROR = 'SET_ERROR',
    SET_ALL_SUPERHEROES = 'SET_ALL_SUPERHEROES',
    LOGIN_USER = 'LOGIN_USER',
    LOGOUT_USER = 'LOGOUT_USER',
    SET_OPEN_MODAL = 'SET_OPEN_MODAL'
}